#
# Serverless Framework Configuration File
# 
# このファイルは、Serverless Frameworkを使用してAWS上でサーバーレスアプリケーションをデプロイするための設定を行います。
# 設定には、プロジェクト名、使用するAWSサービス、環境変数、IAMロールの権限設定などが含まれています。
#
# 詳細な説明:
# - org: サービスを使用するためのServerless Frameworkの組織IDです。
# - service: このプロジェクトの名前で、AWSリソース名にも使用されます。
# - provider: AWSプロバイダーの設定。ランタイムやリージョンを指定します。
# - plugins: 使用するServerless Frameworkプラグインのリスト。
# - functions: Lambda関数の定義とイベントトリガーの設定。
# - custom: サーバーレスプラグインに対するカスタム設定。

# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 00083ns
# "service" is the name of this project. This will also be added to your AWS resource names.
service: UdemyServerlessFramework

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  # stage: ${opt:stage, self:custom.defaultStage}

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function

functions:
  costNotif:
    handler: src/costNotif.handler
    events:
      # 日本時間で毎朝9時
      - schedule: cron(0 0 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URL}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ce:GetCostAndUsage
          - "aws-portal:ViewBilling"
        Resource: "*"

custom:
  serverless-offline:
    noPrependStageInUrl: true
